name: PR Check
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    name: Validate PR title
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@c68b0d5cfaa5c31b21ae08682d9c4f9e8a261d32 # 4.19.1

  enforce-all-checks:
    needs: [validate-pr-title]
    name: Checks
    permissions:
      checks: read
    uses: 3ware/workflows/.github/workflows/wait-for-checks.yaml@c68b0d5cfaa5c31b21ae08682d9c4f9e8a261d32 # 4.19.1
    secrets: inherit
