name: PR Check
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    name: Validate PR title
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@734372a063bf29df3dd2e04315dfad6698248eea # 4.21.1

  enforce-all-checks:
    needs: [validate-pr-title]
    name: Checks
    permissions:
      checks: read
    uses: 3ware/workflows/.github/workflows/wait-for-checks.yaml@734372a063bf29df3dd2e04315dfad6698248eea # 4.21.1
    secrets: inherit
