name: Terraform docs
on:
  workflow_call:
    inputs:
      tf-directory:
        description: Terraform / OpenTofu working directory
        required: true
        type: string

# Disable permissions for all available scopes
permissions: {}

jobs:
  get-temp-token:
    uses: 3ware/workflows/.github/workflows/get-workflow-token.yaml@57a900982a56bebaf91e660a56adb7f021690d15 # v4.0.0
    secrets: inherit

  terraform-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
    needs: [get-temp-token]
    env:
      TF_DOCS_FILE: README.md
      # TODO: Define as an input, because calling workflow could use a different event type
      BRANCH: ${{ github.base_ref }}
    steps:
      - name: Decrypt the installation access token
        id: decrypt-token
        env:
          KEY: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}
        run: |
          DECRYPTED_TOKEN=$(gpg --decrypt --quiet --batch --passphrase "$KEY" \
          --output - <(echo "${{ needs.get-temp-token.outputs.temp-token }}" \
          | base64 --decode))
          echo "::add-mask::$DECRYPTED_TOKEN"
          echo "temp-token=$DECRYPTED_TOKEN" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          token: ${{ steps.decrypt-token.outputs.temp-token }}
          persist-credentials: true # terraform-docs unable to authenticate if false

      - name: Render terraform docs
        id: terraform-docs
        uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # v1.1.0
        with:
          find-dir: ${{ inputs.tf-directory }}
          output-file: ${{ env.TF_DOCS_FILE }}
          output-method: inject

      - name: Push verified commit
        if: ${{ steps.terraform-docs.outputs.num_changed != 0 }}
        id: push-with-sig
        env:
          GITHUB_TOKEN: ${{ steps.decrypt-token.outputs.temp-token }}
        uses: planetscale/ghcommit-action@c7915d6c18d5ce4eb42b0eff3f10a29fe0766e4c # v0.1.44
        with:
          commit_message: "docs(terraform): Update ${{ env.TF_DOCS_FILE }}"
          repo: ${{ github.repository }}
          branch: ${{ env.BRANCH }}
          file_pattern: "terraform/**/${{ env.TF_DOCS_FILE }}"

      - name: Summary with commit failure
        if: ${{ failure() && steps.push-with-sig.outcome == 'failure' }}
        run: |
          echo "### :x: ${{ env.TF_DOCS_FILE }} not updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Commit failure" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Terraform documentation has not been updated" >> $GITHUB_STEP_SUMMARY
          echo "Please review the logs" >> $GITHUB_STEP_SUMMARY

      - name: Summary with document changes
        if: ${{ steps.push-with-sig.conclusion == 'success' }}
        run: |
          echo "### :white_check_mark: Terraform docs updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.terraform-docs.outputs.num_changed }} $TF_DOCS_FILE files updated on $BRANCH" >> $GITHUB_STEP_SUMMARY

      - name: Summary without document changes
        if: ${{ steps.terraform-docs.outputs.num_changed == 0 }}
        run: |
          echo "### :negative_squared_cross_mark: ${{ env.TF_DOCS_FILE }} not updated" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Terraform changes were not detected on this workflow" >> $GITHUB_STEP_SUMMARY
