name: Terraform Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Terraform deployment environment
        required: true
        type: string
      auto-approve-apply:
        description: Auto approve terraform apply; useful in testing environments
        required: true
        type: boolean
      test-destroy:
        description: Run terraform destroy
        required: true
        type: boolean
    secrets:
      provider-credentials:
        description: The ARN of the role for which to fetch credentials
        required: true
      backend-credentials:
        description: Credentials required for remote state
        required: true

# Disable permissions for all available scopes.
permissions: {}

jobs:
  plan-and-apply:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    permissions:
      actions: read # Required to download repository artifact.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      issues: write # Required to create workflow failure issues.
      pull-requests: write # Required to add PR comment and label.

    env:
      TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.backend-credentials }}
      # TODO: Add another input for region
      TF_WORKSPACE: ${{ github.repository }}-aws-us-east-1-${{ inputs.environment }}

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.provider-credentials }}
          role-session-name: ${{ github.repository }}-terraform-deploy

      - name: Setup terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          # TODO: Add tfswitch or other to read value from terraform block
          terraform_version: 1.9.7
          terraform_wrapper: true

      - name: Plan
        uses: devsectop/tf-via-pr@cc83c7bae8216e747bb8c074524665b2416822f5 # v11.4.6
        with:
          arg_chdir: terraform
          arg_command: plan
          arg_lock: false
          arg_out: tfplan-${{ github.head_ref}}-PR${{ github.event.pull_request.number}}-out
          arg_var_file: ${{ inputs.environment }}.tfvars

      # TODO: Add pr comment explaining what to do run trigger apply
      # TODO: Add label tf:plan-approved to PR on approval

      - name: Apply
        # TODO: Run when approved via comment
        uses: devsectop/tf-via-pr@cc83c7bae8216e747bb8c074524665b2416822f5 # v11.4.6
        with:
          arg_chdir: terraform
          arg_command: apply
          arg_auto_approve: ${{ inputs.auto-approve-apply }}
          arg_lock: true
          arg_var_file: ${{ inputs.environment }}.tfvars

      # This plan should not produce a diff
      - name: Check idempotency
        id: idempotency
        uses: devsectop/tf-via-pr@cc83c7bae8216e747bb8c074524665b2416822f5 # v11.4.6
        with:
          arg_chdir: terraform
          arg_command: plan
          arg_lock: false
          arg_detailed_exitcode: true
          arg_out: tfplan-${{ github.head_ref}}-PR${{ github.event.pull_request.number}}-check # Give this plan a different name
          arg_var_file: ${{ inputs.environment }}.tfvars

      - name: Create Issue
        if: ${{ steps.idempotency.outputs.exitcode == 2 }}
        uses: dacbd/create-issue-action@cdb57ab6ff8862aa09fee2be6ba77a59581921c2 # v2.0.0
        with:
          token: ${{ github.token }}
          # TODO: use jobs.<job-id>.environment when reusable; context not available here
          title: ${{ github.workflow }} detected diff during deployment to **PLACEHOLDER** environment
          body: |
            ${{ github.workflow }} workflow run [${{ github.run_id }}](https://github.com/3ware/gitops-2024/actions/runs/11378822294) produced a diff when run via pull request #${{ github.event.pull_request.number }}.

            <details>
            <summary>Outline of changes:</summary>
            <br>

            ```
            ${{ steps.idempotency.outputs.outline }}
            ```

            </details>

            <details>
            <summary>${{ steps.idempotency.outputs.summary }}</summary>
            <br>

            ```
            ${{ steps.idempotency.outputs.last_result }}
            ```

            </details>

          labels: tf:diff

      - name: Destroy
        if: ${{ inputs.test-destroy == true }}
        uses: devsectop/tf-via-pr@cc83c7bae8216e747bb8c074524665b2416822f5 # v11.4.6
        with:
          arg_chdir: terraform
          arg_command: apply
          arg_auto_approve: true
          arg_destroy: true
          arg_lock: true
          arg_var_file: ${{ inputs.environment }}.tfvars

      - name: Diff Error
        if: ${{ steps.idempotency.outputs.exitcode != 0 }}
        run: |
          exit 1
