name: Trunk Upgrade
on:
  schedule:
    - cron: 0 1 * * 1
  workflow_dispatch: {}
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  trunk-upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@8e4c812061ece3fa253bbfa5a80ee1caefa19eb1 # v1.22.9
