name: Checks

on:
  workflow_call: {}

# Disable permissions for all available scopes
permissions: {}

concurrency:
  group: checks-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-all-checks:
    permissions:
      checks: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # check run "auto-approve-pr" is completed with conclusion "cancelled" (unsuccessful) when skipped
          # auto-approve-pr should run on the conclusion of enforce-all-checks, so checks should not check for auto-approve-pr
          # ignore any pattern before '/ enforce-all-checks' for calling workflows
          # For example if the calling workflow job name is 'Checks' the path to ignore is 'Checks / enforce-all-checks'
          ignore_pattern: .*\/ (enforce-all-checks|auto-approve-pr)

  # Approve PR raised by 3ware-release[bot] to upgrade trunk on trunk branches or by 3ware-terraform[bot] on project branches
  # This job will only run if enforce-all-checks job has passed successfully on pull requests. This workflow could be called by
  # a merge_group event: in this case it should not run
  auto-approve-pr:
    if: ${{ github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'auto-approve') }}
    needs: [enforce-all-checks]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.PR_APPROVAL_PAT }}
          review-message: All checks passed. Auto Approved.
