name: Checks

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]
  workflow_call: {}

# Disable permissions for all available scopes
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  enforce-all-checks:
    permissions:
      checks: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@6988432d64ad3f9c2608db4ca16fded1b7d36ead # v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # check run "auto-approve-pr" is completed with conclusion "cancelled" (unsuccessful) when skipped
          # auto-approve-pr should run on the conclusion of enforce-all-checks, so checks should not check for auto-approve-pr
          ignore: auto-approve-pr
          # ignore any pattern before / enforce-all-checks
          ignore_pattern: .*\/enforce-all-checks

  # Approve PR raised by 3ware-release[bot] to upgrade trunk on trunk branches
  # after all checks have passed.
  auto-approve-pr:
    if: ${{ github.actor == '3ware-release[bot]' && github.head_ref == 'trunk-io/update-trunk' }}
    needs: [enforce-all-checks]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.PR_APPROVAL_PAT }}
          review-message: All checks passed. Auto Approved.
